import { createSlice } from '@reduxjs/toolkit';

import { authLogin, signUp } from './auth.actions';
import { history } from 'helpers';

// Initial state for Redux store:
const initialState = {
  user: JSON.parse(localStorage.getItem('user')),
  error: null
};

// Create Redux state slice
const auth = createSlice({
  name: 'auth',
  initialState, // Define initial state
  reducers: {
    logout: (state, action) => {
      state.user = null;
      localStorage.removeItem('user');
      history.navigate('/login');
    }
  },
  extraReducers: {
    // Auth user create actions
    [authLogin.pending]: (state) => {
      state.loading = true;
      state.error = null;
    },
    [authLogin.fulfilled]: (state, { payload }) => {
      state.loading = false;
      if (payload) {
        const user = payload;
        console.log(payload);
        localStorage.setItem('user', JSON.stringify(user));
        state.user = user;
        const { from } = history.location.state || { from: { pathname: '/' } };
        history.navigate(from);
      }
    },
    [authLogin.rejected]: (state, { payload }) => {
      state.loading = false;
      state.error = payload;
    },

    // SignUP Action
    [signUp.pending]: (state) => {
      state.loading = true;
      state.error = null;
    },
    [signUp.fulfilled]: (state, { payload }) => {
      state.loading = false;
      state.success = true;

      const { from } = history.location.state || { from: { pathname: '/' } };
      history.navigate(from);
    },
    [signUp.rejected]: (state, { payload }) => {
      state.loading = false;
      state.error = payload;
    }
  }
});

// Export actions generated by "createSlice()":
export const { logout } = auth.actions;
export const authReducer = auth.reducer;
